Achievements Pull Request
Warzone/mars-api pull request #10
Opened 2023-08-19 06:42 UTC by Mew2K

This is the pull request for the API-side of the achievements implementation.

2023-08-20 03:42 UTC, jellz commented on src/main/kotlin/database/models/Player.kt
> +    val achievements: MutableList<String> = mutableListOf()
I think it would be cool to store the date/time each achievement was reached. It's not strictly necessary though; up to you.

2023-09-06 01:09 UTC, jellz commented on src/main/kotlin/http/achievements/AchievementRoutes.kt
> +fun Route.addAchievement() {
To be consistent with the rest of the codebase, could you combine the routes into one function, like in [this file](https://github.com/Warzone/mars-api/blob/master/src/main/kotlin/http/rank/RankRoutes.kt)?

2023-09-06 01:26 UTC, jellz commented on src/main/kotlin/database/models/Achievement.kt
> +    companion object {
This isn't standard for the codebase as most database queries are directly used in routes without abstraction, but it's not an issue

2024-03-23 03:56 UTC, chatasma approved these changes

2024-03-23 15:19 UTC, jellz requested changes

2024-03-23 15:19 UTC, jellz commented on src/main/kotlin/socket/achievement/PlayerUpdateListener.kt
> +    private suspend fun reply(player: Player, data: PlayerUpdateData, reason: PlayerUpdateReason) {
for consistency, I think this method should be moved to the PlayerContext class (where other MC-bound player-oriented sockets are sent from, such as message sending or XP gains), as an `update` method for example. also, if you do this, the `server` param can be removed from the constructor of this listener (even if this method stays here, I believe that constructor param could be replaced by accessing the server from `PlayerContext#match`)

2024-03-23 15:19 UTC, jellz commented on src/main/kotlin/socket/player/PlayerEvents.kt
> +data class PlayerAchievementData(val player: SimplePlayer, val achievement: String, val completionTime: Long)
could you clarify in the parameter name whether the `achievement` string refers to its ID, name, etc. i.e. `achievementId`, `achievementName`...

2024-03-24 13:05 UTC, jellz approved these changes

2024-03-24 21:29 UTC, merged